# coding: utf-8

"""
    Calculator API

    API for Calculator.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from calculator_api.configuration import Configuration


class Calculation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'operation': 'str',
        'operand1': 'str',
        'operand2': 'str'
    }

    attribute_map = {
        'operation': 'operation',
        'operand1': 'operand1',
        'operand2': 'operand2'
    }

    def __init__(self, operation=None, operand1=None, operand2=None, _configuration=None):  # noqa: E501
        """Calculation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._operation = None
        self._operand1 = None
        self._operand2 = None
        self.discriminator = None

        self.operation = operation
        self.operand1 = operand1
        self.operand2 = operand2

    @property
    def operation(self):
        """Gets the operation of this Calculation.  # noqa: E501

        add, subtract, multiply, divide  # noqa: E501

        :return: The operation of this Calculation.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this Calculation.

        add, subtract, multiply, divide  # noqa: E501

        :param operation: The operation of this Calculation.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def operand1(self):
        """Gets the operand1 of this Calculation.  # noqa: E501

        Operand 1  # noqa: E501

        :return: The operand1 of this Calculation.  # noqa: E501
        :rtype: str
        """
        return self._operand1

    @operand1.setter
    def operand1(self, operand1):
        """Sets the operand1 of this Calculation.

        Operand 1  # noqa: E501

        :param operand1: The operand1 of this Calculation.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and operand1 is None:
            raise ValueError("Invalid value for `operand1`, must not be `None`")  # noqa: E501

        self._operand1 = operand1

    @property
    def operand2(self):
        """Gets the operand2 of this Calculation.  # noqa: E501

        Operand 2  # noqa: E501

        :return: The operand2 of this Calculation.  # noqa: E501
        :rtype: str
        """
        return self._operand2

    @operand2.setter
    def operand2(self, operand2):
        """Sets the operand2 of this Calculation.

        Operand 2  # noqa: E501

        :param operand2: The operand2 of this Calculation.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and operand2 is None:
            raise ValueError("Invalid value for `operand2`, must not be `None`")  # noqa: E501

        self._operand2 = operand2

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Calculation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Calculation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Calculation):
            return True

        return self.to_dict() != other.to_dict()
